version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /workflows/preprocess_AFC_inputs.wdl
    name: "PreprocessAFCInputs"
  - subclass: WDL
    primaryDescriptorPath: /workflows/aFC.wdl
    name: "aFC"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/QuantifyQTLBurden.wdl
    name: "QuantifyQTLBurden"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/CleanQTLBurden.wdl
    name: "CleanQTLBurdenTask"
  - subclass: WDL
    primaryDescriptorPath: /workflows/QTLBurdenQC.wdl
    name: "QTLBurdenQC"
  - subclass: WDL
    primaryDescriptorPath: /workflows/QuantifyQTLBurdenCore.wdl
    name: "QuantifyQTLBurdenCore"
  - subclass: WDL
    primaryDescriptorPath: /workflows/SubsetVCF.wdl
    name: "SubsetVCF"
